name: CI (Dagger)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Dagger version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@main

      - name: Run pipeline
        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e # v8.0.0
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Dagger version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@main

      - name: Run pipeline
        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e # v8.0.0
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: lint

  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Dagger version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@main

      - name: Run pipeline
        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e # v8.0.0
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: check

  without_checkout:
    name: Without Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Get Dagger version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@main

      - name: Run pipeline
        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e # v8.0.0
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          module: github.com/${{ github.repository }}@${{ github.ref }}
          verb: call
          args: check
